### ISSUE TITLE
Missing required module "six" in setup

### ISSUE THREAD

**Issue by iEduard** [eliona-smart-building-assistant/python-eliona-api-client#6]
In order to use the modules, the package _**six**_ is needed. 
Please update the setup file.

`REQUIRES = [
  "urllib3 >= 1.25.3",
  "python-dateutil",
 "six",
]`

<img width="1341" alt="Bildschirmfoto 2022-09-15 um 22 12 24" src="https://user-images.githubusercontent.com/11447389/190499776-81a8b428-b1b3-4a84-b4d6-56be6f3489bb.png">

**Comment by andreas-goebel** [comment]
The setup file is generated and cannot be changed, because during the next generation the setup file will be overwritten.

The error comes from the dateutil parser lib. In the corresponding file _parser.py the `import six` statement is already defined. So it should be help to install the complete dependecies tree for python.

**Comment by spacether** [comment]
This should be fixed when you upgrade openapi-generator to v6.2.1 which comes out soon
Looking at master branch of that openapi-generator, [this PR](https://github.com/OpenAPITools/openapi-generator/pull/13665) pegs `python-dateutil ~= 2.7.0`
And looking at [that python-dateutil release, we see that six should be installed](https://github.com/dateutil/dateutil/blob/2.7.5/setup.py#L67)

**Comment by andreas-goebel** [comment]
This repository is created with an old OpenAPI generator version. All code problems have to changed in the repositoy by hand. There is a second repository using the newest generator version. Please try to use this one: [https://github.com/eliona-smart-building-assistant/python-eliona-api-client2](https://github.com/eliona-smart-building-assistant/python-eliona-api-client2)
