### ISSUE TITLE
Invalid module import Syntax

### ISSUE THREAD

**Issue by iEduard** [eliona-smart-building-assistant/python-eliona-api-client#8]
Invalid module import in the new API. 
Should be "." but is instead "/"

<img width="812" alt="Bildschirmfoto 2022-11-02 um 16 34 47" src="https://user-images.githubusercontent.com/11447389/199533130-8fdc3abd-2b23-43db-82a6-5d880545d621.png">

**Comment by iEduard** [comment]
After serach/replace (eliona/api_client // eliona.api_client) there are other syntax errors in the modules.

<img width="812" alt="Bildschirmfoto 2022-11-02 um 16 39 58" src="https://user-images.githubusercontent.com/11447389/199534311-4ca45de5-bd7a-4820-a7e8-a81271783ea1.png">

**Comment by andreas-goebel** [comment]
This repository is created with an old OpenAPI generator version. All code problems have to changed in the repositoy by hand. There is a second repository using the newest generator version. Please try to use this one: [https://github.com/eliona-smart-building-assistant/python-eliona-api-client2](https://github.com/eliona-smart-building-assistant/python-eliona-api-client2)

**Comment by andreas-goebel** [comment]
This repository is created with an old OpenAPI generator version. All code problems have to changed in the repositoy by hand. There is a second repository using the newest generator version. Please try to use this one: [https://github.com/eliona-smart-building-assistant/python-eliona-api-client2](https://github.com/eliona-smart-building-assistant/python-eliona-api-client2)
