### ISSUE TITLE
Missing include in example

### ISSUE THREAD

**Issue by esc-Leicom** [eliona-smart-building-assistant/python-eliona-api-client#9]
In the example of sending a message this include is missing:

```python
from eliona.api_client.model.attachment import Attachment
```

Link to the Document: 
https://github.com/eliona-smart-building-assistant/python-eliona-api-client/blob/7bf57ac1ba256284ebb8640a598c1664ad2c0104/docs/MessagesApi.md

![Bildschirmfoto 2023-01-04 um 14 35 24](https://user-images.githubusercontent.com/116637086/210567076-8a81c2f2-dda8-4577-8b76-22110a328f24.png)

**Comment by andreas-goebel** [comment]
This repository is created with an old OpenAPI generator version. All code problems have to changed in the repositoy by hand. There is a second repository using the newest generator version. Please try to use this one: [https://github.com/eliona-smart-building-assistant/python-eliona-api-client2](https://github.com/eliona-smart-building-assistant/python-eliona-api-client2)

**Comment by andreas-goebel** [comment]
This repository is created with an old OpenAPI generator version. All code problems have to changed in the repositoy by hand. There is a second repository using the newest generator version. Please try to use this one: [https://github.com/eliona-smart-building-assistant/python-eliona-api-client2](https://github.com/eliona-smart-building-assistant/python-eliona-api-client2)
